apiVersion: apps/v1
kind: Deployment
metadata:
  name: JOB_BASE_NAME
  namespace: NAMESPACE_NAME
  labels:
    app: JOB_BASE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JOB_BASE_NAME
  template:
    metadata:
      labels:
        app: JOB_BASE_NAME
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - image: test-harbor.suixingpay.com/app/JOB_BASE_NAME:BUILD_ID
          imagePullPolicy: IfNotPresent
          name: JOB_BASE_NAME
          ports:
            - containerPort: 80
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: JOB_BASE_NAME
  namespace: NAMESPACE_NAME
spec:
  selector:
    app: JOB_BASE_NAME
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
